### ISSUE TITLE
autotype skips username with custom PASS_FIELD_USERNAME

### ISSUE THREAD

**Issue by ArtemSmaznov** [schmidtandreas/wofi-pass#8]
v23.1.3

# Description
Hi again,

I have finally updated wofi-pass to get the PASS_FIELD_USERNAME changes we worked on and I noticed that auto-typing broke (i was using the script from my last PR up until this point)

# Repro steps
1. `pass edit test`
2. 
```
mypass
login: itisme
```
3. PASS_FIELD_USERNAME="login" in .config/wofi-pass/config
4. `wofi-pass -at`
5. select test

# Expected result
`itisme     mypass`

# Actual result
`     mypass`

**Comment by schmidtandreas** [comment]
The reason for that is, that you have to adjust the `WOFI_PASS_AUTOTYPE` variable. The default value is:
`username :tab :password`
In your case it should be `login :tab :password`.
Is this an acceptable solution for you?

Little bit more background:
`wofi-pass` currently supports only the following keywords for autotype:
- `:tab`
- `:enter`
- `:space`
- `:password`
- `:delay`
- `:otp`

All other keywords (not lead by `:`) are fields and have to match with the entry in pass, even `username` or in your case `login`.

Optional solution for that could be the definition of new keyword for autotype format, like:
`:username` and if this keyword is used by `WOFI_PASS_AUTOTYPE` the `wofi-pass` would output the content for the field defined in `PASS_FIELD_USERNAME`.

Is it still necessary to use the `PASS_FIELD_USERNAME` with the new implementation of `WOFI_PASS_AUTOTYPE` ? Because this approach solves your problem with more flexibility as you can now use any pass field for autotype, whether it is `username` or `login` or something else. Additionally you can even customize it for each entry of pass.

**Comment by ArtemSmaznov** [comment]
didn't have the time yet to fully check the code but I see this in there now
`WOFI_PASS_AUTOTYPE="${WOFI_PASS_AUTOTYPE:-"${PASS_FIELD_USERNAME} :tab :password"}"`
so it looks like the default autotype should respect `PASS_FIELD_USERNAME` but it doesn't for some reason.
I'll try setting it manually in the config after work today but it still feels like a bug tbh.

**Comment by schmidtandreas** [comment]
Yes, you are right. But this works only for command line calls: `PASS_FIELD_USERNAME=login wofi-pass -at`
Not for changes in configuration file.

I agree with you that is not intuitive handling of `PASS_FIELD_USERNAME`. But the implementation of more intuitive handling could be IMO "ugly", because I have to recognize if `WOF_PASS_AUTOTYPE` was set in config file or not and if **not** set but `PASS_FIELD_USERNAME` is changed then the `WOFI_PASS_AUTOTYPE` should be reinitialized.  This make the reading of config file more complicated and depending of pass fields. I would prefer to delete the `PASS_FIELD_USERNAME` handling, because you can define any field for autotype now, independent if it `username` or something else. What do you thing?

**Comment by ArtemSmaznov** [comment]
I see, let me play around with it this evening and I'll get back to you by tomorrow

**Comment by schmidtandreas** [comment]
Hi, I have been thinking a bit and I think the best way to solve this issue is to define the new keyword for autotype `:username` and use this keyword in the default in `WOFI_PASS_AUTOTYPE`. So the username defined by `PASS_FIELD_USERNAME` can be used, on the other hand everyone can still use pass fields directly. I have created a PR #9. See if it works for you.
